### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shrx**
fix typo

### CODE REVIEW

**Comment by winchest3r** [comment]
'select' is probably used as an adjective here. Not a typo.

**Comment by robinj** [comment]
In this case, "select" is being used as an adjective which is perfectly acceptable. Please see this [dictionary entry](http://www.dictionary.com/browse/select)

**Comment by shrx** [comment]
> According to Washington State University Emeritus Professor of English Paul Brians' book Common Errors in English Usage, select is to convey high quality and selected is to convey a specific subset.

http://english.stackexchange.com/a/133489/180144

**Comment by robinj** [comment]
That is just one person's opinion. The OED states: 
>  Selected, chosen out of a larger number, on account of excellence or fitness; picked.

It is likely that the reason that the whole codebase hasn't been released is because it needs cleaning up and is not deemed to be fit for release yet. I am not going to continue arguing, but this PR doesn't seem necessary.

**Comment by paulsapps** [comment]
Selected seems wrong to me, its a select set.

**Comment by RafaelCintron** [comment]
Thank you for the pull request, @shrx. Can you please change the wording to be "This repro contains a subset of files from the implementation ...."  I think this wording makes the intent clearer.

**Comment by shrx** [comment]
@RafaelCintron done :)

**Pull request merged**
